services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - 80:80
      - 443:443
      - 81:81
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./npm_data:/data
      - ./npm_letsencrypt:/etc/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
